In [1]:
import numpy as np

In [4]:
# Can use list of tuple to create an NP array
arr_1 = np.array((range(10)))

arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# To get 2D array use list, tuple returns generators
arr_2 = np.array([range(x, x+4) for x in range(5)])

arr_2

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [51]:
arr_3 = np.zeros((2,3))
print(arr_3)

arr_4 = np.ones((2,4))
print(arr_4)

arr_5 = np.full( (4,5), 7.8765)
print(arr_5)

arr_6 = np.eye(5)
print(arr_6)

# get whatever is in these 18 locations already
arr_7 = np.empty((3,6))
print(arr_7)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7.8765 7.8765 7.8765 7.8765 7.8765]
 [7.8765 7.8765 7.8765 7.8765 7.8765]
 [7.8765 7.8765 7.8765 7.8765 7.8765]
 [7.8765 7.8765 7.8765 7.8765 7.8765]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.49166815e-154  1.73060153e-077  4.44659081e-323  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -1.73060153e-077
   2.68679018e+154  1.25594257e-308]]


In [13]:
# Utility for creating linear intervals (50 of them)
intervals_0_10 = np.linspace(0, 10, 50)

print(intervals_0_10)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [33]:
def integrate(lower, upper, steps, ftn):
    sum = 0
    for x in np.linspace(lower, upper, steps):
        sum += ftn(x)
    return sum*(upper-lower)/steps

In [40]:
integrate(0, 4, 200, lambda x: x**2)

21.386934673366838

## Functions provided by Numpy

In [41]:
np.arange(0, 20, .2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [44]:
# Random numbers from [0, 1]
np.random.random((3,5))

array([[0.3601021 , 0.90228104, 0.53361562, 0.5730166 , 0.17125315],
       [0.32131325, 0.21147523, 0.99548443, 0.25414336, 0.1567171 ],
       [0.80699608, 0.51438834, 0.38182484, 0.61627404, 0.47542071]])

In [47]:
# Random numbers from N(6,2)
np.random.normal(1,2, (4,4))

array([[-1.18155372, -0.82212278, -2.07408094, -0.34285099],
       [-0.88765535,  4.05615375,  0.31237105,  4.01319638],
       [-1.17856128,  1.16031551,  2.34093996, -4.49313888],
       [ 0.04228111,  4.44873778, -1.32810796,  0.24544177]])

In [48]:
# Random numbers from [2, 8)
np.random.randint(0,8, (3,4))

array([[2, 7, 6, 6],
       [4, 2, 2, 3],
       [7, 7, 7, 1]])